### ISSUE TITLE
gnmi_target build fails

### ISSUE THREAD

**Issue by samribeiro** [google/gnxi#5] opened 2017-11-02 11:02 UTC
```
server_test.go:49: error in creating server: nil schema for type *gostruct.Device, value &{<nil> <nil> <nil>}
```

**Comment by larryleguo** [comment] 2017-11-07 19:06
This is caused by ygot library changes. It has been fixed with the new update in https://github.com/google/gnxi/commit/166b19b80ec0eae2b78d3ca84eb93e6c6b46dfd9. will add version control to avoid code broken  later.

**Closed by larryleguo** 2017-11-07 19:06 UTC
